### ISSUE TITLE
Url malformed on redirect

### ISSUE THREAD

**Issue by wespickett** [aurelia/history-browser#13] opened 2015-08-10 21:40 UTC
https://github.com/aurelia/history-browser/blob/master/src/index.js#L212

I think there is a bug on that line where 'fragment' should be 'url'. The bug that appears from this is that when I have a redirect route in a route map like:

```
config.map([
  { route: 'welcome',  moduleId: './welcome',      nav: true, title:'Welcome' },
  { route: '', redirect: 'welcome' }
]);
```

When I visit the route, '', that redirects, it makes the url look like '/#welcome' instead of '/#/welcome'. (missing a '/' after the '#')

Not sure exactly what the variable 'url' is used for, but it seems to fix it mainly because this.root is appended to it with a value of '/'. Not entirely sure what this.root is used for, so if has some other purpose, then it might just need a static '/' appended to fragment.

**Comment by bryanrsmith** [comment] 2015-09-30 05:30
I believe this was resolved by a patch to aurelia/router. I'm not able to reproduce with the current version. Please reopen if I'm mistaken.

**Closed as completed by bryanrsmith** 2015-09-30 05:30 UTC
