### ISSUE TITLE
back button broken on safari mobile

### ISSUE THREAD

**Issue by jdedwards3** [aurelia/history-browser#40] opened 2018-05-04 16:24 UTC
to reproduce run the contact manager tutorial. using safari mobile on iPhone the back button does not trigger canDeactivate as expected.

![candeactivate](https://user-images.githubusercontent.com/16907687/39639200-9373911a-4f96-11e8-933c-71dbe6b96a81.PNG)

this does not work on safari mobile, and on devices where the the promp is shown the browser history is not being maintained

click back
if not on safari mobile prompt shows
click cancel
click back 
if not on safari mobile prompt shows
click ok
user is routed to two history locations back as back button was pressed twice(this might be a separate bug)

Expected: user is only routed one history location back. it seems like the browser history is not being maintained properly, besides the issue of the the back button triggering the prompt on safari mobile.

**Comment by 3cp** [comment] 2018-05-07 23:43
I can reproduce this bug with the code from https://github.com/aurelia/app-contacts, either with original package.json or with updated package.json (with latest aurelia dependencies).

There are two new issues here, not same as the linked issue [router#574](https://github.com/aurelia/router/issues/574) which is solved.

1. history stack is wrong when `canDeactivate()` is rejected (cancelled). Even with cancel on canDeactivate, it somehow affected the pointer to the last history entry, as @jimwards17 stated, it could wire back 2 steps instead of 1.
  * this issue can be reproduced with pushState on or off. It means the bug affects routes with both hash history and native history api.
  * [router#574](https://github.com/aurelia/router/issues/574) is different, it only affects pushState=true. I can confirm it was fixed on app-contacts code, just don't modify any contact details, you can see back/forward buttons work as expected (with pushState on or off).

2. somehow on iOS, `confirm()` doesn't work inside `canDeactivate()`, the `confirm()` call immediately returns `false` without showing any ui. More than that, when it happens, the whole ui is in a broken state.
  * could be an iOS Safari bug
  * I can manually trigger alert/confirm in dev console, they works normally. But once aurelia `canDeactivate()` is processed with a dead `confirm()`. I can no longer manually trigger alert/confirm in dev console, they skip the ui totally.

**Comment by 3cp** [comment] 2018-05-07 23:45
It is kind of a wrong place for this issue. Since it's not related with browser history api.

**Comment by jdedwards3** [comment] 2018-05-07 23:49
@huochunpeng where would be a more appropriate place for this issue?

**Comment by 3cp** [comment] 2018-05-07 23:56
Not exactly sure, could be https://github.com/aurelia/history or https://github.com/aurelia/router.
I guess you don't need to worry about it. Who digs deeper on this issue will move it properly. I probably will try no.1 when I had more spare time in next few days/weeks.

**Comment by davismj** [comment] 2018-05-12 06:37
(1) is a duplicate of https://github.com/aurelia/router/issues/528

@huochunpeng any chance you can take a look at (2) and confirm whether it is an iOS issue or not?

**Comment by 3cp** [comment] 2018-05-12 12:01
I guess (2) is iOS bug. In https://github.com/aurelia/app-contacts/issues/46, There is a related link showing a similar alert/confirm issue on iOS.

**Comment by davismj** [comment] 2018-05-12 12:37
Thanks @huochunpeng great work as always.

**Closed as completed** 2018-05-12 12:37 UTC
Labels: bug
